"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkspaceNavigationDropdown = WorkspaceNavigationDropdown;
exports.WorkspaceNavigationActions = WorkspaceNavigationActions;
const jsx_runtime_1 = require("react/jsx-runtime");
const api_1 = require("@raycast/api");
const RemoteActions_1 = require("./RemoteActions");
const RepositoryDirectoryActions_1 = require("./RepositoryDirectoryActions");
function WorkspaceNavigationDropdown(context) {
    return ((0, jsx_runtime_1.jsxs)(api_1.List.Dropdown, { tooltip: "Select View", value: context.currentView, onChange: (newValue) => context.navigateTo(newValue), children: [(0, jsx_runtime_1.jsx)(api_1.List.Dropdown.Item, { title: "Status", value: "status", keywords: ["diff", "changes", "state", "workspace", "patch"], icon: api_1.Icon.NewDocument }), (0, jsx_runtime_1.jsx)(api_1.List.Dropdown.Item, { title: "Commits", value: "commits", keywords: ["log", "history"], icon: `git-commit.svg` }), (0, jsx_runtime_1.jsx)(api_1.List.Dropdown.Item, { title: "Branches", value: "branches", keywords: ["graph", "remote"], icon: `git-branch.svg` }), (0, jsx_runtime_1.jsx)(api_1.List.Dropdown.Item, { title: "Tags", value: "tags", keywords: ["releases", "annotations"], icon: api_1.Icon.Tag }), (0, jsx_runtime_1.jsx)(api_1.List.Dropdown.Item, { title: "Remotes", value: "remotes", keywords: ["origin"], icon: api_1.Icon.Network }), (0, jsx_runtime_1.jsx)(api_1.List.Dropdown.Item, { title: "Stashes", value: "stashes", keywords: ["bookmark"], icon: api_1.Icon.Bookmark }), (0, jsx_runtime_1.jsx)(api_1.List.Dropdown.Item, { title: "Files", value: "files", keywords: ["history", "ls-files", "workspace", "project"], icon: api_1.Icon.Clock })] }));
}
function WorkspaceNavigationActions(context) {
    return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsxs)(api_1.ActionPanel.Section, { title: "Navigation", children: [(0, jsx_runtime_1.jsx)(api_1.Action, { title: "Go to Status", onAction: () => context.navigateTo("status"), icon: api_1.Icon.NewDocument, shortcut: { modifiers: ["cmd"], key: "1" } }), (0, jsx_runtime_1.jsx)(api_1.Action, { title: "Go to Commits", onAction: () => context.navigateTo("commits"), icon: `git-commit.svg`, shortcut: { modifiers: ["cmd"], key: "2" } }), (0, jsx_runtime_1.jsx)(api_1.Action, { title: "Go to Branches", onAction: () => context.navigateTo("branches"), icon: `git-branch.svg`, shortcut: { modifiers: ["cmd"], key: "3" } }), (0, jsx_runtime_1.jsx)(api_1.Action, { title: "Go to Remotes", onAction: () => context.navigateTo("remotes"), icon: api_1.Icon.Network, shortcut: { modifiers: ["cmd"], key: "4" } }), (0, jsx_runtime_1.jsx)(api_1.Action, { title: "Go to Stash", onAction: () => context.navigateTo("stashes"), icon: api_1.Icon.Bookmark, shortcut: { modifiers: ["cmd"], key: "5" } }), (0, jsx_runtime_1.jsx)(api_1.Action, { title: "Go to Tags", onAction: () => context.navigateTo("tags"), icon: api_1.Icon.Tag, shortcut: { modifiers: ["cmd"], key: "6" } }), (0, jsx_runtime_1.jsx)(api_1.Action, { title: "Go to Files", onAction: () => context.navigateTo("files"), icon: api_1.Icon.Folder, shortcut: { modifiers: ["cmd"], key: "0" } })] }), (0, jsx_runtime_1.jsx)(RepositoryDirectoryActions_1.RepositoryDirectoryActions, { repositoryPath: context.gitManager.repoPath }), context.remotes.data && Object.keys(context.remotes.data).map((remote) => ((0, jsx_runtime_1.jsxs)(api_1.ActionPanel.Section, { title: `${remote} • ${context.remotes.data[remote].organizationName}/${context.remotes.data[remote].repositoryName}`, children: [(0, jsx_runtime_1.jsx)(RemoteActions_1.RemoteOpenPullRequestAction, { remote: context.remotes.data[remote] }), context.branches.data.currentBranch && ((0, jsx_runtime_1.jsx)(RemoteActions_1.RemoteCreatePullRequestAction, { branch: context.branches.data.currentBranch?.name, remote: context.remotes.data[remote] }))] }, remote)))] }));
}
